
image yoga_1_a_slow = Movie(play="images/videos/yoga/yoga_1_a_slow.webm", start_image="images/videos/yoga/yoga_1_a_slow.webp",size=(1920,1080))
image yoga_1_a_normal = Movie(play="images/videos/yoga/yoga_1_a_normal.webm", start_image="images/videos/yoga/yoga_1_a_normal.webp",size=(1920,1080))
image yoga_1_a_fast = Movie(play="images/videos/yoga/yoga_1_a_fast.webm", start_image="images/videos/yoga/yoga_1_a_fast.webp",size=(1920,1080))
image yoga_1_b_slow = Movie(play="images/videos/yoga/yoga_1_b_slow.webm", start_image="images/videos/yoga/yoga_1_b_slow.webp",size=(1920,1080))
image yoga_1_b_normal = Movie(play="images/videos/yoga/yoga_1_b_normal.webm", start_image="images/videos/yoga/yoga_1_b_normal.webp",size=(1920,1080))
image yoga_1_b_fast = Movie(play="images/videos/yoga/yoga_1_b_fast.webm", start_image="images/videos/yoga/yoga_1_b_fast.webp",size=(1920,1080))
image yoga_2_a_slow = Movie(play="images/videos/yoga/yoga_2_a_slow.webm", start_image="images/videos/yoga/yoga_2_a_slow.webp")
image yoga_2_a_normal = Movie(play="images/videos/yoga/yoga_2_a_normal.webm", start_image="images/videos/yoga/yoga_2_a_normal.webp")
image yoga_2_a_fast = Movie(play="images/videos/yoga/yoga_2_a_fast.webm", start_image="images/videos/yoga/yoga_2_a_fast.webp")
image yoga_2_b_slow = Movie(play="images/videos/yoga/yoga_2_b_slow.webm", start_image="images/videos/yoga/yoga_2_b_slow.webp")
image yoga_2_b_normal = Movie(play="images/videos/yoga/yoga_2_b_normal.webm", start_image="images/videos/yoga/yoga_2_b_normal.webp")
image yoga_2_b_fast = Movie(play="images/videos/yoga/yoga_2_b_fast.webm", start_image="images/videos/yoga/yoga_2_b_fast.webp")