
image image1 = "gallery/gallery_1_1.jpg"
image image1_2 = "gallery/gallery_1_2.jpg"
image image2 = "gallery/gallery_2.jpg"
image image3 = "gallery/gallery_3_1.jpg"
image image3_2 = "gallery/gallery_3_2.jpg"
image image4 = "gallery/gallery_4.jpg"
image image5 = "gallery/gallery_5.jpg"
image image6 = "gallery/gallery_6.jpg"
image image7 = "gallery/gallery_7.jpg"
image image8 = "gallery/gallery_8.jpg"
image image9 = "gallery/gallery_9.jpg"
image image10 = "gallery/gallery_10.jpg"

image thumb1= "gallery/thumb_1.jpg"
image thumb2= "gallery/thumb_2.jpg"
image thumb3= "gallery/thumb_3.jpg"
image thumb4= "gallery/thumb_4.jpg"
image thumb5= "gallery/thumb_5.jpg"
image thumb6= "gallery/thumb_6.jpg"
image thumb7= "gallery/thumb_7.jpg"
image thumb8= "gallery/thumb_8.jpg"
image thumb9= "gallery/thumb_9.jpg"
image thumb10= "gallery/thumb_10.jpg"